apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend-dev
  namespace: dev
spec:
  replicas: 1 # Dev chỉ cần 1 replica
  selector:
    matchLabels:
      app: todo-frontend-dev
  template:
    metadata:
      labels:
        app: todo-frontend-dev
        env: dev
    spec:
      containers:
        - name: todo-frontend
          image: taithanh/todo-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

          # Cấu hình tài nguyên nhẹ hơn cho dev
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
              cpu: "100m"

          # Mount config volume
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js

      # Volumes từ ConfigMap
      volumes:
        - name: config-volume
          configMap:
            name: frontend-config # Tên ConfigMap Dev

---
apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: todo-frontend-dev
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32000 # Dev port range
