apiVersion: v1
kind: Service
metadata:
  name: todo-service-metrics
  namespace: prod
spec:
  type: NodePort
  selector:
    app: todo-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31180
      name: metrics

---
apiVersion: v1
kind: Service
metadata:
  name: user-service-metrics
  namespace: prod
spec:
  type: NodePort
  selector:
    app: user-service
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 31181
      name: metrics

---
apiVersion: v1
kind: Service
metadata:
  name: stats-service-metrics
  namespace: prod
spec:
  type: NodePort
  selector:
    app: stats-service
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 31182
      name: metrics

---
apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics-nodeport
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: kube-state-metrics
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31280
      name: metrics
