apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kube-vip-ds
  template:
    metadata:
      labels:
        name: kube-vip-ds
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  # SỬA 1: Đổi master thành control-plane để tránh Warning
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
                  # SỬA 2: Xóa dòng check worker để đảm bảo nó chạy trên node hiện tại của bạn
                  # (Nếu node bạn là worker thuần túy thì xóa luôn cả block affinity này cũng được)
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      serviceAccountName: kube-vip
      hostNetwork: true
      containers:
        - name: kube-vip
          image: ghcr.io/kube-vip/kube-vip:v0.6.0
          imagePullPolicy: Always
          args:
            - manager
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          env:
            - name: vip_interface
              value: ens33

            - name: vip_arp
              value: "true"
            - name: cp_enable
              value: "false"
            - name: cp_namespace
              value: kube-system
            - name: svc_enable
              value: "true"
            - name: address
              value: 192.168.40.200-192.168.40.210
