apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kube-vip-ds
  template:
    metadata:
      labels:
        name: kube-vip-ds
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
                  - key: node-role.kubernetes.io/worker
                    operator: DoesNotExist
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      serviceAccountName: kube-vip
      hostNetwork: true
      containers:
        - name: kube-vip
          image: ghcr.io/kube-vip/kube-vip:v0.6.0
          imagePullPolicy: Always
          args:
            - manager
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          env:
            # Tên card mạng
            - name: vip_interface
              value: ens33

            # Cấu hình chế độ ARP
            - name: vip_arp
              value: "true"

            #Tắt chế độ Control Plane
            - name: cp_enable
              value: "false"
            - name: cp_namespace
              value: kube-system

            #Bật Service LoadBalancer
            - name: svc_enable
              value: "true"

            #Dải IP VIP bạn cấp phát
            - name: address
              value: 192.168.40.200-192.168.40.210
