# --- 1. Cấu hình Database ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: db
data:
  POSTGRES_DB: todo_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password123
---
# --- 2. Triển khai Postgres Database ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      # QUAN TRỌNG: Ép chạy trên Node 3 (Backend)
      nodeSelector:
        role: backend
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: db-config
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgredb
      volumes:
      - name: postgredb
        hostPath:
          path: /mnt/data/mysql # Đảm bảo thư mục này đã tạo trên node 3
---
# --- 3. Postgres Service (Nội bộ) ---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: db
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
---
# --- 4. Triển khai Java Backend ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      # QUAN TRỌNG: Ép chạy trên Node 3 (Backend)
      nodeSelector:
        role: backend
      containers:
      - name: todo-backend
        # Image V4 mới nhất của bạn
        image: taithanh/todo-backend:v4
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        # Cấu hình kết nối sang Postgres Service
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-service:5432/todo_db"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "password123"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: "org.postgresql.Driver"
---
# --- 5. Backend Service (Mở cổng 30006) ---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend-service
  namespace: db
spec:
  type: NodePort
  selector:
    app: todo-backend
  ports:
    - name: api
      port: 8080
      targetPort: 8080
      nodePort: 30006
---
# --- 6. Kết nối Prometheus (Giám sát) ---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: todo-backend
  namespaceSelector:
    matchNames:
      - db
  endpoints:
  - port: api
    path: /actuator/prometheus
    interval: 15s
