apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
  namespace: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      # QUAN TRỌNG: Ép chạy trên Node 4 (Frontend)
      nodeSelector:
        role: frontend
      containers:
      - name: todo-frontend
        # Image Frontend V1 của bạn
        image: taithanh/todo-frontend:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-service
  namespace: db
spec:
  type: NodePort
  selector:
    app: todo-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30007 # Cổng truy cập Web
