apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend-prod
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-frontend-prod
  template:
    metadata:
      labels:
        app: todo-frontend-prod
    spec:
      # --- Affinity & Anti-Affinity
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - app
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - todo-frontend-prod
              topologyKey: "kubernetes.io/hostname"

      # --- Container Configuration ---
      containers:
        - name: todo-frontend
          image: taithanh/todo-frontend:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 80

          # Cấu hình tài nguyên
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"

          # Gắn file config vào container
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js

      # --- Volumes
      volumes:
        - name: config-volume
          configMap:
            name: frontend-config # Tên ConfigMap (Prod)
---
apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-service
  namespace: prod
spec:
  #type: LoadBalancer
  #loadBalancerIP: 192.168.40.203
  type: ClusterIP
  selector:
    app: todo-frontend-prod
  ports:
    - name: http
      port: 80
      targetPort: 80
      #nodePort: 31000
