apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-service
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-service
  template:
    metadata:
      labels:
        app: todo-service
      # Prometheus metrics
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/todos/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      # --- CẤU HÌNH AFFINITY
      affinity:
        # 1. Ưu tiên chạy trên nhóm App (Worker 2, 3)
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - app

        # 2. Tự động né nhau (preferred - cho phép scale > số nodes)
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - todo-service
                topologyKey: "kubernetes.io/hostname"

      containers:
        - name: todo-backend
          image: taithanh/todo-backend:v6
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          # Cấu hình kết nối Database
          env:
            - name: SPRING_DATASOURCE_URL
              # "postgres-service" là tên Service của DB ở bước trước
              value: "jdbc:postgresql://postgres-service.databases.svc.cluster.local:5432/todo_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password123"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"

          # Giới hạn tài nguyên (Java cần nhiều RAM lúc khởi động)
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"

          # Health Check: Chờ Java 30s mới kiểm tra
          readinessProbe:
            httpGet:
              path: /todos/actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: prod
spec:
  #type: LoadBalancer
  #loadBalancerIP: 192.168.40.200
  type: ClusterIP
  selector:
    app: todo-service
  ports:
    - port: 8080
      targetPort: 8080
      #nodePort: 31080
